=head1 WWW-ReviewBoard-API

Provides a Perl-ish API to the
L<Review Board REST API v2|http://www.reviewboard.org/docs/manual/dev/webapi/>

=head2 Goal

It should support an 'explorative' interaction. For example, to print out the
names and email addresses for all the people assigned to review request #42:

    my $rb = WWW::ReviewBoard::API->new(
        url => 'http://reviews.mydomain.com/api/',
        username => 'admin',
        password => 'r3view!'
    );

    foreach my $user ($rb->review_request(42)->target_people) {
        say $user->name . ' - ' . $user->email;
    }

Or to print the summary for all pending review requests:

    foreach my $review ($rb->review_requests(status => 'pending')) {
        say $review->summary;
    }

For more details start by reading at the WWW::ReviewBoard::API POD.

=head2 Testing

The unit tests should be all you need to be confident that the distribution
will install.

However, there are tests which are designed to be used against a running Review
Board instance. These tests exist under t/1_functional.

Note that this should be a dedicated test instance as reviews, users, etc. will
be created automatically.

The instance to use can be defined by setting the following environment
variables:

=over

=item REVIEWBOARD_URL

=item REVIEWBOARD_USER

=item REVIEWBOARD_PASS

=back
